  #most fundamential concepts of tensor 

In [ ]:
import tensorflow as tf
print(tf.__version__)


2.4.1


In [ ]:
#creating tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#checking the number of dimension ndim
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) #specify parametar with dtype parametar
another_matrix 

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#NUMBER OF DIMENSIONS IS HOW ELEMENTS ARE THERE IN THE SHAPE

In [ ]:
#creating a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

scalar single number  0 dim 

vector number with direction 1 dim

matrix 2 dim array

tensor n-dime array 



In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangealble_tensor = tf.constant([10, 7])
changeable_tensor, unchangealble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
#how about we try .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#creating RANDOM TENSORS

random1 = tf.random.Generator.from_seed(42) #set seed for REPRODUCIBILITY
random1 = random1.normal(shape=(3, 2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random2 = tf.random.Generator.from_seed(42)      #
random2 = random2.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random1, random2, random1 == random2    #are they equal?

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuffle the order of elements in a tensor (for data so the order is better for learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

In [ ]:
#shuffle non shuffled tensor AS LONG IS THE FIRST DIMENSION
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

five random tensor and shuffle them (homework)


In [ ]:
#NUMPY ONES

In [ ]:
import numpy as np

tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

turn numpy array into tensors and main diff in numpy and tf that tensors can be run on gpu

In [ ]:
import numpy as np



numpy_A = np.arange(1, 25, dtype=np.int32)       #create np array beatween 1 and 25

#X = tf.constant(some_matrix)   #capital for matrix or tensor
#y = tf.constant(vector)         #non capital for vectors 


In [ ]:
A = tf.constant(numpy_A,shape=[3,8])
#B = tf.constant(numpy_A)
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [ ]:
#GETTING INFORMATIONS FROM TENSORS

#shape
#create rank4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor



<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
 rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

GET VARIOUS ATRIBUTES OF A TENSOR

In [ ]:
#atributes
print('Datatype of every element:', rank_4_tensor.dtype)
print('Number of dimensions rank:', rank_4_tensor.ndim)
print('Shape of a tensor:', rank_4_tensor.shape)
print('Elements along X axis:', rank_4_tensor.shape[0])
print('Elements along last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in a tensor:', tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimensions rank: 4
Shape of a tensor: (2, 3, 4, 5)
Elements along X axis: 2
Elements along last axis: 5
Total number of elements in a tensor: 120


tensors can be indexed just like python lists

In [ ]:

# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
rank_4_tensor[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first elelment from each dimeension except for the final one
rank_4_tensor[:1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

ADDING AN EXTRA DIMENSION 

In [ ]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [ ]:
#get the last element of each row of rank 2 tensor
rank_2_tensor[:, -1]



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

R E S H A P I N G 
ADDING AN EXTRA DIMENSION TO TENSOR

In [ ]:
#adding extra dimension to rank2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

in numpy is NONE in tf is tf.newaxis 

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) #expand 0-axis



<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

dimension changes

TENSOR MANIPULATION :::::: OPERATIONS

In [ ]:
 #you can add values to a tensor using the addition operator

 tensor = tf.constant([[10, 7], [3, 4]])
 tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#multiplication of a tensor
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#using the tensorflow BUILT-IN FUNCITION
tf.multiply(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

MATRIX MULTIPLICATIONS ONE OF THE MOST COMMON TENOSR OPERATIONS
ELEMENT WISE OPERATIONS 

In [ ]:
#matrix mul and dot product
#multiply matrices means dot prod
#dot prod multu dot prod and matching members

print(tensor)
tf.matmul(tensor, tensor)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#same with python operator @
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

this is element wise

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

tensors with different shapes

In [ ]:
#create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:

#changing the shape of the Y matrix
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

MATMUL


In [ ]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

homework - recreating tensor multiplication in tensorflow

In [ ]:
H = tf.constant([[1, 2, 5],
                [7, 2, 1],
                [3, 3, 3]])
M = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])
tf.matmul(H, M)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

same goes with python code, just using THIS: @

In [ ]:
H @ M

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

multiplication of matrices: 
>>>differernt shape

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#Create a tensor (3, 2) tensor shape
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
#Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

TRANSPOSITION

In [ ]:
tf.matmul(tf.transpose(X), Y)

DOT PRODUCT

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
#perform matrix multiplication between X and Y transposed
tf.matmul(X, tf.transpose(Y))


In [ ]:
#perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
#check the values of Y, reshaped Y and transposed Y
print("Normal Y")
print(Y, "/n")

print("Y reshaped to (2, 3)")
print(tf.reshape(Y, (2, 3)), "/n")

print("Y transposed:")
print(tf.transpose(Y))


In [ ]:
tf.matmul(X, tf.transpose(Y))


AGGRAGATING TENSORS

In [ ]:
#aggregating = from multiple values down to smaller amount of values
#getting the absolute values
D = tf.constant([-7, -10])
D


In [ ]:
#create absolute
tf.abs(D)

getting the minimum, maximum, the main, the sum:::

In [ ]:
#creating the random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
tf.size(E), E.shape, E.ndim 

In [ ]:
#find a minimum in tensorflow
tf.reduce_min(E)
#in nampa its np.min(E) !!!!  



In [ ]:
tf.reduce_max(E)


In [ ]:
#find mean
tf.reduce_mean(E)

In [ ]:
#sum
tf.reduce_sum(E)

exercise is to find the variants and standard deviation of E tensor using tf method. 

In [ ]:
#creating new tensor for positioning min and max

In [ ]:
#positional max and min
#at which index in the row the min or max value occures
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F 


In [ ]:
#Find the positional maximun (refered as argmax)
tf.argmax(F)

In [ ]:
#index of largest value
F[tf.argmax(F)]

In [ ]:
#find the max value of F
tf.reduce_max(F)


In [ ]:
 F[tf.argmax(F)] == tf.reduce_max(F)


REMOVING DIMENSIONS 

In [ ]:
#squeezing a tensor (remuving ALL SINGLE dimensions)
#create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

In [ ]:
G.shape

In [ ]:
G_sqeezed = tf.squeeze(G)
G_sqeezed, G_sqeezed.shape



ONE HOT ENCODING


In [ ]:
some_list = [0, 1, 2, 3] #for example colors

#one hot encode this
tf.one_hot(some_list, depth=4)


In [ ]:
#using on and off value and passing them differently
#specify values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love tensors", off_value="also trains and bananas")


tf.math

In [ ]:
#squaring, log, square root
#create new tensor
H = tf.range(1, 10)
H

In [ ]:
#sqare it
tf.square(H)


In [ ]:
#find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

In [ ]:
#find a log 
tf.math.log(tf.cast(H, dtype=tf.float32))

TENSORS AND NUMPY <3 <3 <3 

In [ ]:
#create a numpa array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#convert tensor back to nampa array
np.array(J), type(np.array(J))


(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#convert tensor J to a NAMPA array
J.numpy(), type(J.numpy())


(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [ ]:
J.numpy()[0]


3.0

In [ ]:
#default types are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
#check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)